package provider

import (
	"regexp"
	"strings"

	"github.com/mingzaily/bitwarden-backup/internal/model"
	"github.com/mingzaily/bitwarden-backup/internal/safety"
)

var legacyBackupTimestampPattern = regexp.MustCompile(`^\d{8}_\d{6}\.\d{9}$`)

func destinationMedium(providerType string) string {
	switch providerType {
	case "local":
		return "local"
	case "webdav":
		return "webdav"
	case "s3":
		return "oss"
	default:
		return ""
	}
}

func renderBackupFilename(ctx BackupContext) string {
	raw := model.RenderFilenameTemplate(
		ctx.FilenameTemplate,
		safety.Filename(ctx.TaskName),
		ctx.Timestamp,
		destinationMedium(ctx.Destination.Type),
	)
	filename := safety.Filename(raw)
	if !strings.HasSuffix(strings.ToLower(filename), ".json") {
		filename += ".json"
	}
	return filename
}

// backupFilenamePattern returns the exact filename shape generated by the
// current task/template. The only variable part is the required 14-digit
// timestamp. Matching against this shape prevents retention from deleting an
// unrelated JSON file that happens to contain a timestamp.
func backupFilenamePattern(ctx BackupContext) *regexp.Regexp {
	const timeToken = "VaultSyncTimeToken"

	raw := model.NormalizeFilenameTemplate(ctx.FilenameTemplate)
	raw = strings.ReplaceAll(raw, "{task_name}", safety.Filename(ctx.TaskName))
	raw = strings.ReplaceAll(raw, "{medium}", destinationMedium(ctx.Destination.Type))
	raw = strings.ReplaceAll(raw, "{time}", timeToken)
	filename := safety.Filename(raw)
	if !strings.Contains(filename, timeToken) {
		return nil
	}
	pattern := regexp.QuoteMeta(filename)
	pattern = strings.ReplaceAll(pattern, regexp.QuoteMeta(timeToken), `\d{14}`)
	return regexp.MustCompile("^" + pattern + "$")
}

func matchesBackupFilename(name string, ctx BackupContext) bool {
	if !strings.HasSuffix(strings.ToLower(name), ".json") {
		return false
	}

	if pattern := backupFilenamePattern(ctx); pattern != nil && pattern.MatchString(name) {
		return true
	}

	// Keep compatibility with files generated before the filename template
	// setting existed, but scope the legacy match to the current task name.
	legacyPrefix := "backup_" + safety.Filename(ctx.TaskName) + "_"
	if !strings.HasPrefix(name, legacyPrefix) {
		return false
	}
	stem := strings.TrimSuffix(name[len(legacyPrefix):], ".json")
	return legacyBackupTimestampPattern.MatchString(stem)
}
